In [1]:
import numpy as np
import pandas as pd

Creating a DataFrame

In [4]:
data = {
    "Name":['John','Anna','Peter','Linda'],
    "Age":[20,34,29,42],
    "City":['New York', "paris", "Berlin", "London"],
    "Salary":[65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [5]:
df

    Name  Age      City  Salary
0   John   20  New York   65000
1   Anna   34     paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [35]:
data_list = [
    ['John','Anna','Peter','Linda'],
    [20,34,29,42],
    ['New York', "paris", "Berlin", "London"],
    [65000, 70000, 62000, 85000]
]
df2 = pd.DataFrame(data_list).T
df2

       0   1         2      3
0   John  20  New York  65000
1   Anna  34     paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [36]:
columns = ["Name","Age","City","Salary"]
# df2 = pd.DataFrame(data_list, columns= columns).T
df2.columns = columns

In [16]:
df2

    Name Age      City Salary
0   John  20  New York  65000
1   Anna  34     paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

Selections and Indexing of Columns

In [20]:
# df2['Name']
df2['City']

0    New York
1       paris
2      Berlin
3      London
Name: City, dtype: object

In [21]:
df2[['Name','City']]

    Name      City
0   John  New York
1   Anna     paris
2  Peter    Berlin
3  Linda    London

Creating a new Column

In [22]:
df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]

In [23]:
df2

    Name Age      City Salary Designation
0   John  20  New York  65000      Doctor
1   Anna  34     paris  70000        Eng.
2  Peter  29    Berlin  62000      Doctor
3  Linda  42    London  85000        Eng.

Removing Column

In [28]:
df2.drop('Designation',axis = 1)

    Name Age      City Salary
0   John  20  New York  65000
1   Anna  34     paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [29]:
df2

    Name Age      City Salary Designation
0   John  20  New York  65000      Doctor
1   Anna  34     paris  70000        Eng.
2  Peter  29    Berlin  62000      Doctor
3  Linda  42    London  85000        Eng.

In [31]:
df2.drop("Designation", axis=1, inplace=True)
df2

    Name Age      City Salary
0   John  20  New York  65000
1   Anna  34     paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [32]:
df2.drop(["City","Salary"], axis=1, inplace=True)

In [33]:
df2

    Name Age
0   John  20
1   Anna  34
2  Peter  29
3  Linda  42

In [34]:
df2.drop(0,axis=0)

    Name Age
1   Anna  34
2  Peter  29
3  Linda  42

Selecting Rows

In [37]:
df2

    Name Age      City Salary
0   John  20  New York  65000
1   Anna  34     paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [39]:
df2.loc[0]

Name          John
Age             20
City      New York
Salary       65000
Name: 0, dtype: object

In [40]:
df2.loc[[0,1]]

   Name Age      City Salary
0  John  20  New York  65000
1  Anna  34     paris  70000

In [41]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

Selecting Subsets of Rows and Columns

In [43]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     paris   70000

In [44]:
df.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

Conditional Selection

In [45]:
df2

    Name Age      City Salary
0   John  20  New York  65000
1   Anna  34     paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [48]:
#I only want to see those people whose age is above 30
df2[df2["Age"] > 30]

    Name Age    City Salary
1   Anna  34   paris  70000
3  Linda  42  London  85000

In [52]:
# I only want people whose age is above 30 and their city must be peris.
df2[(df2["Age"]>30) & (df2["City"] == "paris")]

   Name Age   City Salary
1  Anna  34  paris  70000