In [9]:
import numpy as np
import pandas as pd

In [10]:
df = pd.read_csv(r'anime.csv')

In [11]:
df.head()

   Rank                                     Title  Score
0     1  Fullmetal Alchemist: Brotherhood(64 eps)   9.10
1     2                       Steins;Gate(12 eps)   9.05
2     3      Attack on Titan Final Season(12 eps)   9.03
3     4                        Death Note(12 eps)   8.95
4     5                   Hunter x Hunter(12 eps)   9.02

In [19]:
# Make a new Column for episode count
# df.loc[2]
df.loc[2]['Title']

'Attack on Titan Final Season(12 eps)'

In [20]:
txt = df.loc[2]['Title']

def extract_episodes(txt):
    check = False
    data = ""
    for i in txt:
        if i == ')':
            check = False
            return data
        if check == True:
            data += i
        if i == '(':
            check = True

In [21]:
df['Title'].apply(extract_episodes)

0     64 eps
1     12 eps
2     12 eps
3     12 eps
4     12 eps
5     12 eps
6     12 eps
7     12 eps
8     12 eps
9     12 eps
10    12 eps
11    12 eps
12    12 eps
13    12 eps
14    12 eps
15    12 eps
16    12 eps
17    12 eps
18    12 eps
19    12 eps
20    16 eps
21    16 eps
22    16 eps
23    16 eps
24    16 eps
25    16 eps
26    16 eps
27    16 eps
28    16 eps
29    16 eps
30    16 eps
31    16 eps
32    16 eps
33    16 eps
34    16 eps
35    16 eps
36    16 eps
37    16 eps
38    16 eps
39      None
40      None
41      None
42      None
43      None
44      None
45    16 eps
46    16 eps
47    16 eps
48    16 eps
49    16 eps
Name: Title, dtype: object

In [22]:
df['Episodes'] = df['Title'].apply(extract_episodes)

In [23]:
df

    Rank                                     Title  Score Episodes
0      1  Fullmetal Alchemist: Brotherhood(64 eps)   9.10   64 eps
1      2                       Steins;Gate(12 eps)   9.05   12 eps
2      3      Attack on Titan Final Season(12 eps)   9.03   12 eps
3      4                        Death Note(12 eps)   8.95   12 eps
4      5                   Hunter x Hunter(12 eps)   9.02   12 eps
5      6                           Gintama(12 eps)   8.98   12 eps
6      7                        Code Geass(12 eps)   8.91   12 eps
7      8                  Naruto Shippuden(12 eps)   8.85   12 eps
8      9                         One Piece(12 eps)   8.92   12 eps
9     10                      Demon Slayer(12 eps)   8.80   12 eps
10    11                    Jujutsu Kaisen(12 eps)   8.79   12 eps
11    12                  My Hero Academia(12 eps)   8.50   12 eps
12    13                       Tokyo Ghoul(12 eps)   8.45   12 eps
13    14                      Black Clover(12 eps)   8.40   12 eps
14    15                            Bleach(12 eps)   8.55   12 eps
15    16                     Dragon Ball Z(12 eps)   8.70   12 eps
16    17                      Spy x Family(12 eps)   8.65   12 eps
17    18                      Vinland Saga(12 eps)   8.88   12 eps
18    19                           Monster(12 eps)   8.87   12 eps
19    20                      Cowboy Bebop(12 eps)   8.75   12 eps
20    21                         Haikyuu!!(16 eps)   8.82   16 eps
21    22                    Mob Psycho 100(16 eps)   8.81   16 eps
22    23                           Re:Zero(16 eps)   8.60   16 eps
23    24                         Fate Zero(16 eps)   8.68   16 eps
24    25                          Parasyte(16 eps)   8.58   16 eps
25    26                            Erased(16 eps)   8.54   16 eps
26    27                 Your Lie in April(16 eps)   8.66   16 eps
27    28               Clannad After Story(16 eps)   8.93   16 eps
28    29                         Toradora!(16 eps)   8.30   16 eps
29    30                      Angel Beats!(16 eps)   8.25   16 eps
30    31                   No Game No Life(16 eps)   8.35   16 eps
31    32                         Dr. Stone(16 eps)   8.32   16 eps
32    33                        Fire Force(16 eps)   7.95   16 eps
33    34                         Blue Lock(16 eps)   8.20   16 eps
34    35                      Chainsaw Man(16 eps)   8.55   16 eps
35    36                 Hellsing Ultimate(16 eps)   8.42   16 eps
36    37            The Promised Neverland(16 eps)   8.50   16 eps
37    38                     Made in Abyss(16 eps)   8.71   16 eps
38    39                       Psycho-Pass(16 eps)   8.40   16 eps
39    40                            Akame ga Kill!   7.90     None
40    41                          Bungo Stray Dogs   8.28     None
41    42                  Kaguya-sama: Love is War   8.84     None
42    43                                  Horimiya   8.22     None
43    44             The Rising of the Shield Hero   8.05     None
44    45                                  Overlord   8.15     None
45    46                    Mushoku Tensei(16 eps)   8.73   16 eps
46    47                     Solo Leveling(16 eps)   8.78   16 eps
47    48     Frieren: Beyond Journey's End(16 eps)   9.15   16 eps
48    49                        Oshi no Ko(16 eps)   8.76   16 eps
49    50                       Kaiju No. 8(16 eps)   8.18   16 eps

In [25]:
df['Episodes'] = df['Episodes'].str.replace(" eps","")

In [26]:
df

    Rank                                     Title  Score Episodes
0      1  Fullmetal Alchemist: Brotherhood(64 eps)   9.10       64
1      2                       Steins;Gate(12 eps)   9.05       12
2      3      Attack on Titan Final Season(12 eps)   9.03       12
3      4                        Death Note(12 eps)   8.95       12
4      5                   Hunter x Hunter(12 eps)   9.02       12
5      6                           Gintama(12 eps)   8.98       12
6      7                        Code Geass(12 eps)   8.91       12
7      8                  Naruto Shippuden(12 eps)   8.85       12
8      9                         One Piece(12 eps)   8.92       12
9     10                      Demon Slayer(12 eps)   8.80       12
10    11                    Jujutsu Kaisen(12 eps)   8.79       12
11    12                  My Hero Academia(12 eps)   8.50       12
12    13                       Tokyo Ghoul(12 eps)   8.45       12
13    14                      Black Clover(12 eps)   8.40       12
14    15                            Bleach(12 eps)   8.55       12
15    16                     Dragon Ball Z(12 eps)   8.70       12
16    17                      Spy x Family(12 eps)   8.65       12
17    18                      Vinland Saga(12 eps)   8.88       12
18    19                           Monster(12 eps)   8.87       12
19    20                      Cowboy Bebop(12 eps)   8.75       12
20    21                         Haikyuu!!(16 eps)   8.82       16
21    22                    Mob Psycho 100(16 eps)   8.81       16
22    23                           Re:Zero(16 eps)   8.60       16
23    24                         Fate Zero(16 eps)   8.68       16
24    25                          Parasyte(16 eps)   8.58       16
25    26                            Erased(16 eps)   8.54       16
26    27                 Your Lie in April(16 eps)   8.66       16
27    28               Clannad After Story(16 eps)   8.93       16
28    29                         Toradora!(16 eps)   8.30       16
29    30                      Angel Beats!(16 eps)   8.25       16
30    31                   No Game No Life(16 eps)   8.35       16
31    32                         Dr. Stone(16 eps)   8.32       16
32    33                        Fire Force(16 eps)   7.95       16
33    34                         Blue Lock(16 eps)   8.20       16
34    35                      Chainsaw Man(16 eps)   8.55       16
35    36                 Hellsing Ultimate(16 eps)   8.42       16
36    37            The Promised Neverland(16 eps)   8.50       16
37    38                     Made in Abyss(16 eps)   8.71       16
38    39                       Psycho-Pass(16 eps)   8.40       16
39    40                            Akame ga Kill!   7.90     None
40    41                          Bungo Stray Dogs   8.28     None
41    42                  Kaguya-sama: Love is War   8.84     None
42    43                                  Horimiya   8.22     None
43    44             The Rising of the Shield Hero   8.05     None
44    45                                  Overlord   8.15     None
45    46                    Mushoku Tensei(16 eps)   8.73       16
46    47                     Solo Leveling(16 eps)   8.78       16
47    48     Frieren: Beyond Journey's End(16 eps)   9.15       16
48    49                        Oshi no Ko(16 eps)   8.76       16
49    50                       Kaiju No. 8(16 eps)   8.18       16

In [28]:
type(df.loc[0]['Episodes'])

str

In [31]:
df['Episodes'] = df['Episodes'].fillna(0).astype(int)
df

    Rank                                     Title  Score  Episodes
0      1  Fullmetal Alchemist: Brotherhood(64 eps)   9.10        64
1      2                       Steins;Gate(12 eps)   9.05        12
2      3      Attack on Titan Final Season(12 eps)   9.03        12
3      4                        Death Note(12 eps)   8.95        12
4      5                   Hunter x Hunter(12 eps)   9.02        12
5      6                           Gintama(12 eps)   8.98        12
6      7                        Code Geass(12 eps)   8.91        12
7      8                  Naruto Shippuden(12 eps)   8.85        12
8      9                         One Piece(12 eps)   8.92        12
9     10                      Demon Slayer(12 eps)   8.80        12
10    11                    Jujutsu Kaisen(12 eps)   8.79        12
11    12                  My Hero Academia(12 eps)   8.50        12
12    13                       Tokyo Ghoul(12 eps)   8.45        12
13    14                      Black Clover(12 eps)   8.40        12
14    15                            Bleach(12 eps)   8.55        12
15    16                     Dragon Ball Z(12 eps)   8.70        12
16    17                      Spy x Family(12 eps)   8.65        12
17    18                      Vinland Saga(12 eps)   8.88        12
18    19                           Monster(12 eps)   8.87        12
19    20                      Cowboy Bebop(12 eps)   8.75        12
20    21                         Haikyuu!!(16 eps)   8.82        16
21    22                    Mob Psycho 100(16 eps)   8.81        16
22    23                           Re:Zero(16 eps)   8.60        16
23    24                         Fate Zero(16 eps)   8.68        16
24    25                          Parasyte(16 eps)   8.58        16
25    26                            Erased(16 eps)   8.54        16
26    27                 Your Lie in April(16 eps)   8.66        16
27    28               Clannad After Story(16 eps)   8.93        16
28    29                         Toradora!(16 eps)   8.30        16
29    30                      Angel Beats!(16 eps)   8.25        16
30    31                   No Game No Life(16 eps)   8.35        16
31    32                         Dr. Stone(16 eps)   8.32        16
32    33                        Fire Force(16 eps)   7.95        16
33    34                         Blue Lock(16 eps)   8.20        16
34    35                      Chainsaw Man(16 eps)   8.55        16
35    36                 Hellsing Ultimate(16 eps)   8.42        16
36    37            The Promised Neverland(16 eps)   8.50        16
37    38                     Made in Abyss(16 eps)   8.71        16
38    39                       Psycho-Pass(16 eps)   8.40        16
39    40                            Akame ga Kill!   7.90         0
40    41                          Bungo Stray Dogs   8.28         0
41    42                  Kaguya-sama: Love is War   8.84         0
42    43                                  Horimiya   8.22         0
43    44             The Rising of the Shield Hero   8.05         0
44    45                                  Overlord   8.15         0
45    46                    Mushoku Tensei(16 eps)   8.73        16
46    47                     Solo Leveling(16 eps)   8.78        16
47    48     Frieren: Beyond Journey's End(16 eps)   9.15        16
48    49                        Oshi no Ko(16 eps)   8.76        16
49    50                       Kaiju No. 8(16 eps)   8.18        16

In [32]:
type(df.loc[0]['Episodes'])

numpy.int64

In [35]:
# Which anime has the highest score

df[df['Score'] == df['Score'].max()]
# df[df['Score'] == df['Score'].max()]['Title']

    Rank                                  Title  Score  Episodes
47    48  Frieren: Beyond Journey's End(16 eps)   9.15        16

In [42]:
# Give me top 5 highest scoring anime
# df['Score'].unique
top5 = df.sort_values(by='Score', ascending=False).head(5)
# print(top5)
top5[['Title','Score']]

                                       Title  Score
47     Frieren: Beyond Journey's End(16 eps)   9.15
0   Fullmetal Alchemist: Brotherhood(64 eps)   9.10
1                        Steins;Gate(12 eps)   9.05
2       Attack on Titan Final Season(12 eps)   9.03
4                    Hunter x Hunter(12 eps)   9.02

In [43]:
top5 = df.nlargest(5, 'Score')
top5

    Rank                                     Title  Score  Episodes
47    48     Frieren: Beyond Journey's End(16 eps)   9.15        16
0      1  Fullmetal Alchemist: Brotherhood(64 eps)   9.10        64
1      2                       Steins;Gate(12 eps)   9.05        12
2      3      Attack on Titan Final Season(12 eps)   9.03        12
4      5                   Hunter x Hunter(12 eps)   9.02        12

In [47]:
# Which anime has Highest Episod count
df[df['Episodes'] == df['Episodes'].max()]
# df['Episodes'] == df['Episodes'].max()

   Rank                                     Title  Score  Episodes
0     1  Fullmetal Alchemist: Brotherhood(64 eps)    9.1        64

In [49]:
#Which is top 4 episode count
top5Episode = df.nlargest(4,'Episodes')
top5Episode

    Rank                                     Title  Score  Episodes
0      1  Fullmetal Alchemist: Brotherhood(64 eps)   9.10        64
20    21                         Haikyuu!!(16 eps)   8.82        16
21    22                    Mob Psycho 100(16 eps)   8.81        16
22    23                           Re:Zero(16 eps)   8.60        16