In [1]:
import numpy as np
import pandas as pd

**GroupBy**

In [14]:
data = {
    'Category':['A','B','A','B','A','B','A','B'],
    'Store':['S1','S1','S2','S2','S1','S2','S2','S1'],
    'Sales':[100,200,150,250,120,180,200,300],
    'Quantity':[10,15,12,18,8,20,15,25],
    'Date':pd.date_range('2023-01-01',periods=8)
}
df = pd.DataFrame(data)

In [15]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [18]:
#Group By Category and calculate the sum of Sales
cat = df.groupby('Category')
cat

In [19]:
for i,v in cat:
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [20]:
cat_sum = df.groupby('Category')['Sales'].sum()
cat_sum

Category
A    570
B    930
Name: Sales, dtype: int64

In [21]:
# Group by Store calculate the sum of Sales
sales_sum = df.groupby('Store')['Sales'].sum()
sales_sum

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [23]:
#Group by multiple columns
# Group by Category and Store

cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

**Aggregation**

In [24]:
df['Sales'].mean()

np.float64(187.5)

In [ ]:
#median mode min max count std

In [26]:
df['Sales'].agg(['sum','mean','min','max','count','std','median'])

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

In [32]:
df['Sales'].mod(7)

0    2
1    4
2    3
3    5
4    1
5    5
6    4
7    6
Name: Sales, dtype: int64

In [34]:
#Count Records per Category
df.groupby('Category').size()

Category
A    4
B    4
dtype: int64

In [35]:
#Highest Sale in Each Category
df.groupby('Category')['Sales'].max()

Category
A    200
B    300
Name: Sales, dtype: int64

In [37]:
#Sort Groups by Total Sales
df.groupby('Category')['Sales'].sum().sort_values(
    ascending = False
)

Category
B    930
A    570
Name: Sales, dtype: int64

In [38]:
#Top Selling Store
df.groupby('Store')['Sales'].sum()

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [39]:
#Range(custom Aggregation)
df.groupby('Category')['Sales'].agg(
    lambda x: x.max() - x.min()
)

Category
A    100
B    120
Name: Sales, dtype: int64

In [40]:
#Filter Groups (show only Sales > 600)

df.groupby('Category').filter(
    lambda x: x['Sales'].sum() > 600
)

  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [42]:
# Category ke ander sabse zyada sale wali row
idx = df.groupby('Category')['Sales'].idxmax()
df.loc[idx]

  Category Store  Sales  Quantity       Date
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08